/**
 * `lisa update` — bring this machine's lisa up to date.
 *
 * Two halves, in order, because the second depends on the first:
 *
 *   1. Rebuild lisa itself, when it is a git checkout: `git pull`, `npm install`,
 *      `npm run build`. Skipped with a note for an `npm i -g lisa-cli` install, where
 *      there is no working tree to pull into — npm owns that upgrade.
 *   2. Re-apply the harness wiring, for every harness already wired, *at the scope and
 *      mode it is actually wired in*. A new lisa version usually ships a new brief, and a
 *      brief that no longer matches the tools it describes is worse than an old one.
 *
 * The second half is deliberately not "install everything". Wiring a harness the user
 * never chose would be a surprise, so update only refreshes what is already there and
 * says which harnesses it skipped and why.
 */

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import pc from "picocolors";
import { type RuntimeContext } from "../paths.js";
import { packageRoot } from "../templates.js";
import {
  HARNESSES,
  applyChanges,
  changeKind,
  installTarget,
  wiredMode,
  type FileChange,
  type Harness,
  type InstallScope,
  type ToolsMode,
} from "../harness/index.js";

export interface UpdateOptions {
  config?: string;
  /** Report what would change, write nothing, run nothing. */
  check?: boolean;
  /** Skip the rebuild half and only re-apply wiring. */
  noBuild?: boolean;
}

/** Is the lisa package a git working tree we can pull, or an installed artifact? */
export function checkoutRoot(): string | null {
  const root = packageRoot();
  return fs.existsSync(path.join(root, ".git")) ? root : null;
}

function run(cmd: string, args: string[], cwd: string): boolean {
  console.log(pc.dim(`  $ ${cmd} ${args.join(" ")}`));
  const r = spawnSync(cmd, args, { cwd, stdio: "inherit" });
  if (r.error || r.status !== 0) {
    console.log(pc.red(`  ${cmd} failed${r.status ? ` (exit ${r.status})` : ""} — stopping before the wiring step.`));
    return false;
  }
  return true;
}

/**
 * Pull and rebuild the checkout.
 *
 * Returns false when a step failed, and the caller stops: re-applying wiring generated by
 * a half-built tree would write briefs describing tools that may not exist.
 */
function rebuild(root: string, check: boolean): boolean {
  console.log(pc.bold("Rebuilding lisa") + pc.dim(`  ${root}`));
  if (check) {
    console.log(pc.dim("  (--check: would run git pull, npm install, npm run build)"));
    return true;
  }
  // `--ff-only` so a dirty or diverged checkout fails loudly instead of opening a merge
  // the user did not ask for in a directory they may not have been thinking about.
  return run("git", ["pull", "--ff-only"], root) && run("npm", ["install"], root) && run("npm", ["run", "build"], root);
}

interface Row {
  harness: Harness;
  scope: InstallScope | null;
  mode: ToolsMode | null;
  changes: FileChange[];
  skipped?: string;
}

/** Plan the refresh for every harness, preserving whatever scope and mode it is wired in. */
function planAll(ctx: RuntimeContext): Row[] {
  return HARNESSES.map((harness) => {
    let state;
    try {
      state = wiredMode(harness, ctx);
    } catch (e) {
      return { harness, scope: null, mode: null, changes: [], skipped: (e as Error).message.split("\n")[0] };
    }
    if (state.status === "not-wired") return { harness, scope: null, mode: null, changes: [], skipped: "not wired" };
    // A stale harness has no single wired mode to preserve, so `wiredMode` reports a null
    // one. Refreshing it at the default is right: that is what `lisa install` would write
    // today, and "stale" already means nothing on disk currently matches any combination.
    const scope = state.scope ?? undefined;
    const mode = state.mode ?? undefined;
    try {
      return { harness, scope: scope ?? null, mode: mode ?? null, changes: harness.plan(installTarget(ctx, { scope, mode })) };
    } catch (e) {
      return { harness, scope: scope ?? null, mode: mode ?? null, changes: [], skipped: (e as Error).message.split("\n")[0] };
    }
  });
}

export async function updateCommand(opts: UpdateOptions, ctx: RuntimeContext): Promise<void> {
  const root = checkoutRoot();

  if (opts.noBuild) {
    console.log(pc.dim("Skipping the rebuild (--no-build).\n"));
  } else if (root) {
    if (!rebuild(root, Boolean(opts.check))) {
      process.exitCode = 1;
      return;
    }
    console.log("");
  } else {
    console.log(
      pc.dim("lisa isn't a git checkout here, so there's nothing to rebuild — upgrade it with `npm i -g lisa-cli@latest`.\n"),
    );
  }

  console.log(pc.bold("Harness wiring"));
  const rows = planAll(ctx);
  const width = Math.max(...HARNESSES.map((h) => h.id.length)) + 2;
  let written = 0;

  for (const row of rows) {
    const label = row.harness.id.padEnd(width);
    if (row.skipped) {
      console.log(`  ${label}${pc.dim(row.skipped)}`);
      continue;
    }
    const where = pc.dim(`${row.scope ?? "?"}/${row.mode ?? "?"}`.padEnd(16));
    const pending = row.changes.filter((c) => changeKind(c) !== "unchanged");
    if (!pending.length) {
      console.log(`  ${label}${where}${pc.green("up to date")}`);
      continue;
    }
    if (opts.check) {
      console.log(`  ${label}${where}${pc.yellow(`${pending.length} file(s) would change`)}`);
      for (const c of pending) console.log(`    ${pc.dim(c.path)}`);
      continue;
    }
    const applied = applyChanges(row.changes);
    written += applied.length;
    console.log(`  ${label}${where}${pc.yellow(`updated ${applied.length} file(s)`)}`);
    for (const c of applied) console.log(`    ${pc.dim(c.path)}`);
  }

  const wired = rows.filter((r) => !r.skipped);
  if (!wired.length) {
    console.log(pc.dim("\n  Nothing is wired yet — run `lisa install claude-code` to set this machine up."));
    return;
  }
  if (opts.check) {
    const drifted = wired.filter((r) => r.changes.some((c) => changeKind(c) !== "unchanged"));
    console.log(drifted.length ? pc.yellow(`\n${drifted.length} harness(es) out of date. Run \`lisa update\` to apply.`) : pc.green("\nEverything is up to date."));
    // Non-zero so CI can gate on drift, the same way a linter's --check does.
    if (drifted.length) process.exitCode = 1;
    return;
  }
  console.log(written ? pc.green(`\n${written} file(s) updated. Restart your agent so it re-reads them.`) : pc.green("\nEverything was already up to date."));
}
